services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: produtos_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    environment:
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000

      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: products_app
      DB_USERNAME: postgres
      DB_PASSWORD: ddlk15Ph8JD6a7xOP
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: produtos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: products_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ddlk15Ph8JD6a7xOP
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products_app"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
